name: Semantic Release for Apps

on:
  push:
    branches:
      - master

permissions: write-all

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        run: npx semantic-release-monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB2 }}
