name: Semantic Release for Apps

on:
  push:
    branches:
      - master

permissions: write-all

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: [ecs-forgate-simple, eks-modules, ecs-modules]  # Replace with your directory names

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update tag format
        id: update_tag_format
        run: |
          DIRECTORY=${{ matrix.directory }}
          echo "::set-output name=tag_format::${DIRECTORY}-v\${version}"

      - name: Determine CHANGELOG.md path
        id: changelog_path
        run: |
          DIRECTORY=${{ matrix.directory }}
          if [[ -f "${DIRECTORY}/CHANGELOG.md" ]]; then
            echo "::set-output name=path::${DIRECTORY}/CHANGELOG.md"
          else
            echo "::set-output name=path::"
          fi

      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB2 }}
        with:
          tag_format: '${{ steps.update_tag_format.outputs.tag_format }}'
          additional_packages: |
            ['@semantic-release/changelog', '@semantic-release/git']
          plugins: |
            [
              '@semantic-release/commit-analyzer',
              '@semantic-release/release-notes-generator',
              ['@semantic-release/changelog', { changelogTitle: '# CHANGELOG', "changelogFile": "${{ steps.changelog_path.outputs.path }}" }],
              '@semantic-release/github',
              ['@semantic-release/git', { "assets": ["${{ steps.changelog_path.outputs.path }}"] }]
            ]
          branches: |
            [
              'master'
            ]
        if: steps.changelog_path.outputs.path != ''

      - name: Semantic Release Output Summary
        id: semantic_summary
        run: |
          echo "### Semantic Version = ${{ steps.semantic.outputs.release-version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ toJson(steps.semantic.outputs) }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true
